# Nombre de la acción
name: Crear archivo de bienvenida

# Descripción de la acción
description: Crear un archivo de bienvenida en el repositorio

inputs:
  # Nombre del repositorio
  repository:
    # Descripción del input
    description: Nombre del repositorio
    # Indicar si el input es requerido
    required: true

# Ejecución de la acción
runs:
  # Tipo de ejecución (en este caso, bash)
  using: "composite"
  steps:
    - name: Crear archivo de bienvenida
  run: |
    echo "Hola, bienvenido al repositorio de $INPUT_REPOSITORY" > bienvenida.txt
    if [ $? -eq 0 ]; then
      echo "Archivo creado con éxito: bienvenida.txt"
    else
      echo "Error al crear el archivo"
    fi
  # Directorio de trabajo
  working-directory: .