# Nombre de la acción
name: Crear archivo de bienvenida

# Ejecución de la acción
runs:
  # Tipo de ejecución (en este caso, bash)
  using: "composite"
  steps:
    - run: |
        echo "Hola, bienvenido al repositorio de $INPUT_REPOSITORY" > bienvenida.txt
        if [ $? -eq 0 ]; then
          echo "Archivo creado con éxito: bienvenida.txt"
        else
          echo "Error al crear el archivo"
        fi
      shell: bash