name: Actions2

on:
  workflow_dispatch:

jobs:
  action1:
    runs-on: labs-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Acción1
        uses: ./.github/actions/action_2
