name: Actions1

on:
  workflow_dispatch:

jobs:
  action:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Acción1
        uses: ./.github/actions/action_1
