# Definimos el nombre de la tarea ficticia y la notificación
name: Tarea ficticia y notificación

# Seleccionamos el evento que dispara la tarea (push a la rama main)
on:
  workflow_dispatch:

# Definimos el trabajo que se realizará (tarea-ficticia)
jobs:
  tarea-ficticia:
    # Seleccionamos el entorno de ejecución (labs-runner)
    runs-on: labs-runner
    # Definimos los pasos que se realizarán en la tarea
    steps:
      # Paso 1: Tarea ficticia
      - name: Tarea ficticia
        # Ejecutamos un comando que simula una tarea ficticia
        run: |          
          echo "Realizando tarea ficticia..."
          sleep 5          
          echo "Tarea ficticia completada"
      # Paso 2: Notificación
      - name: Notificación exito
        # Ejecutamos un comando que simula la notificación
        # Utilizamos curl para enviar una solicitud POST a la URL de notificación
        # Definimos el tipo de contenido de la solicitud (application/json)
        # Definimos el cuerpo de la solicitud (estado y evento)
        if: job.status == 'success'
        run: |
          echo "Enviando notificación..."
          curl -X POST \
            http://URL.com/notificacion \
            -H 'Content-Type: application/json' \

            -d '{"estado": "exito", "evento": "'"$GITHUB_EVENT_NAME"'"}'
          echo "Notificación enviada"

      - name: Notificación
        # Ejecutamos un comando que simula la notificación
        # Utilizamos curl para enviar una solicitud POST a la URL de notificación
        # Definimos el tipo de contenido de la solicitud (application/json)
        # Definimos el cuerpo de la solicitud (estado y evento)
        if: job.status != 'success'
        run: |
          echo "Enviando notificación..."
          curl -X POST \
            http://URL.com/notificacion \
            -H 'Content-Type: application/json' \

            -d '{"estado": "exito", "evento": "'"$GITHUB_EVENT_NAME"'"}'
          echo "Notificación enviada"


          