# Definimos el nombre del workflow
name: Información del runner

# Seleccionamos el evento que dispara el workflow (push a la rama main)
on:
  push:
    branches:
      - main
      - actions_ws1

# Definimos el trabajo que se va a ejecutar
jobs:
  informacion-del-runner:
    # Seleccionamos el entorno de ejecución (labs-runner)
    runs-on: labs-runner
    # Definimos los pasos que se van a ejecutar
    steps:
      # Paso 1: Imprimir información del runner
      - name: Imprimir información del runner
        # Comando que se va a ejecutar
        # Imprimimos el sistema operativo, la arquitectura del sistema,
        # el espacio en disco disponible en la raíz del sistema
        run: |
          echo "Sistema operativo: ${RUNNER_OS}"
          echo "Arquitectura: ${RUNNER_ARCH}"
          echo "Espacio en disco disponible: $(df -h / | awk 'NR==2 {print $4}')"