name: Deploy to environment
on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy to environment
        run: echo "Deploying to ${{ inputs.env }}"