name: Deploy to environment
on:
  workflow_call:
    inputs:
      env:
        type: string

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy to ${{ inputs.env }}
        run: echo "Deploying to ${{ inputs.env }}"
