name: Deploy to environment
on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true

jobs:
  deploy:
    runs-on: labs-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to ${{ inputs.env }}
        run: |
          echo "Deploying to ${{ inputs.env }}"
