name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'staging'
        type: choice
        options:
          - production
          - staging

jobs:
  deploy:
    runs-on: labs-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print environment
        run: echo "Deploying to ${{ github.event.inputs.environment }}"