name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Mensaje personalizado'
        required: true

jobs:
  print-message:
    runs-on: labs-runner
    steps:
      - name: Imprimir mensaje
        run: echo "El mensaje es ${{ github.inputs.message }}"