name: Multitarea manual

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: labs-runner
    steps:
      - name: Mostrar fecha y hora actual
        run: date
      - name: Crear archivo de texto
        run: echo "Hola, mundo!" > archivo.txt
      - name: Listar archivos en el directorio actual
        run: ls -l
      - name: Hacer commit y push
        env:
          REPO_TOKEN: ${{ secrets.MY_PAT }}
        run: |
          git config --global user.name "David_Faustino"
          git config --global user.email "dfaustino@stemdo.io"
          git init
          git remote add origin https://$REPO_TOKEN@github.com/stemdo-labs/github-actions-exercises-Dfausben.git
          git pull origin main
          git commit -m "Primer commit"
          git branch -M main
          git push -u origin main
