name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: labs-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run build
        run: |
          echo "Building..."

  deploy:
    needs: build
    runs-on: labs-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run deploy
        run: |
          echo "Deploying..."