name: Multitarea manual

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: labs-runner
    steps:
      - name: Mostrar fecha y hora actual
        run: date
      - name: Crear archivo de texto
        run: echo "Hola, mundo!" > archivo.txt
      - name: Listar archivos en el directorio actual
        run: ls -l
      - name: Hacer commit y push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Actualización automática"
          git push