name: Deploy to Environments

on:
  push:
    branches:
      - main
      - dev


jobs:
  deploy:
    runs-on: dfausben_runner
    steps:
      - name: Comprobar rama
        uses: ./.github/workflows/deploy-enviromment.yml
        with:
          env: ${{ github.ref.name }}
          # if: github.ref.name == 'main' || github.ref.name == 'develop' || startsWith(github.ref.name, 'release/')
