name: Deploy to Environments

on:
  push:
    branches:
      - main
      - dev

jobs:
       - name: Comprobar rama
         uses: ./.github/workflows/deploy-enviromment
         with:
           env: ${{ github.ref.name }}

