name: Deploy to Environments

on:
  push:
    branches:
      - main
      - dev
      - 'release/*'

jobs:
  deploy:
  runs-on: labs-runner
  steps:
    uses: ./.github/workflows/deploy-enviromment.yml
    with:
    # if: github.ref.name == 'main' || github.ref.name == 'develop' || startsWith(github.ref.name, 'release/')
      env: ${{ github.ref.name }}
    
    