name: Deploy to Environments

on:
  push:
    branches:
      - main
      - dev
      - 'release/*'

jobs:
  deploy:
    uses: ./.github/workflows/deploy-enviromment.yml
    with:
      if: github.event.branch == 'main' || github.event.branch == 'develop' || startsWith(github.event.branch, 'release/')
      env: ${{ github.event.branch }}
    