name: Deploy to Environments

on:
  push:
    branches:
      - main
      - dev


jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Comprobar rama
        uses: ./.github/workflows/deploy-enviromment
        with:
          env: ${{ github.ref.name }}
          # if: github.ref.name == 'main' || github.ref.name == 'develop' || startsWith(github.ref.name, 'release/')
