name: Random Number Workflow

on:
  workflow_dispatch:

jobs:
  random-number:
    runs-on: labs-runner
    steps:
      - name: Generate Random Number
        run: |
          RANDOM_NUMBER=$(( RANDOM % 100 + 1 ))
          echo "RANDOM_NUMBER=$RANDOM_NUMBER" >> $GITHUB_ENV

      - name: Conditional Step
        if: env.RANDOM_NUMBER > 50
        run: |
          echo "El número es mayor a 50"